### ISSUE TITLE
Instances don't appear from imported ontologies

### ISSUE THREAD

**Issue by johardi** [protegeproject/ontograf#13]
The screenshot below shows an ontology with two import declarations, where the instance 'bolero' comes from an imported ontology. OntoGraf failed to show the instance (but the arc type showed 'has individual' does exist). The plugin was able to show the instance if the imported ontology was used instead.
![screen shot 2016-05-05 at 9 37 54 am](https://cloud.githubusercontent.com/assets/5062950/15049914/b7d4de04-12a5-11e6-915c-b700d1a2e1af.png)

**Comment by AniaDavid** [comment]
please help to solve this quickly i need this to do my report, it is soon, appreciate the efforts really so much

**Comment by AniaDavid** [comment]
I need to say that _sometimes  _individuals from imported ontologies are displayed, it was working on the past (one week ago more or less), but now not.

**Comment by AniaDavid** [comment]
so it is fixed now? If so, which Protege should i install please?

**Comment by johardi** [comment]
please check you email for the plugin jar and the installation instruction.

**Comment by todayokay** [comment]
May I have that jar as well? Is problem fixed?

**Comment by matthewhorridge** [comment]
Have you tried the latest release at this link?

https://github.com/protegeproject/ontograf/releases

**Comment by lsarni** [comment]
It seems like the solution for this issue fixed this #16 and #20 too. **Would it be possible to create a new release with the fixes?**

In case it helps, I created a pull request #21 with the changes needed for the new release to automatically upgrade the plugin for Protege users.

I have downloaded master and tested it an it is correctly displaying the relationships established on the imported ontologies and the instances of the classes:

## Using Ontograf 2.0.3
![untitle1d](https://user-images.githubusercontent.com/15196342/40591370-4102595e-61e6-11e8-88d2-965adfa02ef8.png)


## Using Ontograf 2.0.4-SNAPSHOT (master until commit https://github.com/protegeproject/ontograf/commit/866cc3a4ed2a4aee45e638bbb636bf688d196d5e , the one that closed this issue)
![untitled](https://user-images.githubusercontent.com/15196342/40591368-40b251a2-61e6-11e8-8056-a612c06d482d.png)
